In [ ]:
import tensorflow as tf
from tensorflow import keras

from keras.datasets import fashion_mnist
from keras.utils.np_utils import to_categorical

#load dataset
(trainX, trainY), (testX, testY) = fashion_mnist.load_data()
#load train and test dataset
def load_dataset():
    #load dataset
    (trainX, trainY), (testX, testY) = fashion_mnist.load_data()
    #reshape dataset to have a single channel
    trainX = trainX.reshape((trainX.shape[0], 28, 28, 1))
    testX = testX.reshape((test.shape[0], 28, 28, 1))
    trainY = to_categorical(trainY)
    testY = to_categorical(testY)
    return trainX, trainY, testX, testY
    

seed = 9

from sklearn.model_selection import StratifiedShuffleSplit

data_split = StratifiedShuffleSplit(test_size = 0.5,random_state = seed)
for train_index, test_index in data_split.split(trainX, trainY):
    
    split_data_92, split_data_8 = trainX[train_index], trainX[test_index]
    
    split_label_92, split_label_8 = trainY[train_index], trainY[test_index]
train_test_split = StratifiedShuffleSplit(test_size = 0.3,random_state = seed)

#data splitting
for train_index, test_index in train_test_split.split(split_data_8,split_label_8):
    
    train_data_70, test_data_30 = split_data_8[train_index], split_data_8[test_index]
    
    train_label_70, test_label_30 = split_label_8[train_index], split_label_8[test_index]
train_data = train_data_70

train_labels = train_label_70

test_data = test_data_30

test_labels = test_label_30
print('train_data : ',train_data.shape)
print('train_labels : ',train_labels.shape)
print('test_data : ',test_data.shape)
print('test_labels : ',test_labels.shape)

import numpy as np

#data preprocessing
#PREPROCESSING WITH NORMALIZATION FUNCTION
def normalize(data, eps=1e-8):
    data -= data.mean(axis=(0,1,2),keepdims=True)
    std = np.sqrt(data.var(axis=(0, 1, 2), ddof=1, keepdims=True))
    std[std < eps] = 1
    data /= std
    return data
train_data=train_data.astype('float64')
test_data=test_data.astype('float64')
#calling the function
train_data = normalize(train_data)
test_data = normalize(test_data)
#printing the slope of train data and test data
print('train_data: ', train_data.shape)
print('test_data: ',test_data.shape)


#PREPROCESSING WITH PCA
#computing whitening matrix
train_data_flat = train_data.reshape(train_data.shape[0], -1)
test_data_flat = test_data.reshape(test_data.shape[0], -1)
print('train_data_flat: ',train_data_flat.shape)
print('test_data_flat: ',test_data_flat.shape)

train_data_flat_t = train_data_flat
test_data_flat_t = test_data_flat

from sklearn.decomposition import PCA

train_data_pca =PCA(n_components=min(train_data_flat.shape)).fit_transform(train_data_flat)
test_data_pca =PCA(n_components=min(test_data_flat.shape)).fit_transform(test_data_flat)
print(train_data_pca.shape)
print(test_data_pca.shape)


#PREPROCESSING WITH SVD
from skimage import color

def svdFeatures(input_data):
    svdArray_input_data=[]
    size = input_data.shape[0]
    for i in range (0,size):
        img=color.rgb2gray(input_data[i])
        u, s, v = np.linalg.svd(img, full_matrices=False)
        S=[s[i] for i in range(28)]
        svdArray_input_data.append(S)
        svdMatrix_input_data=np.matrix(svdArray_input_data)
    return svdMatrix_input_data
#apply SVD for train and test data
train_data_svd=svdFeatures(train_data)
test_data_svd=svdFeatures(test_data)
print(train_data_svd.shape)
print(test_data_svd.shape)



4431872/4422102 [==============================] - 0s 0us/step
train_data :  (21000, 28, 28)
train_labels :  (21000,)
test_data :  (9000, 28, 28)
test_labels :  (9000,)
train_data:  (21000, 28, 28)
test_data:  (9000, 28, 28)
train_data_flat:  (21000, 784)
test_data_flat:  (9000, 784)
(21000, 784)
(9000, 784)
(21000, 28)
(9000, 28)


In [ ]:
#By using data preprocessed with NORMALIZATION FUNCTION

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
MLP1=MLPClassifier()
MLP1.fit(train_data_flat_t,train_labels)

mlp_predict1 = MLP1.predict(test_data_flat_t)
score1 = MLP1.score(test_data_flat_t,test_labels)
print("score", score1)

Confusion_Matrix1 = metrics.confusion_matrix(test_labels, mlp_predict1)
print("Confusion Matrix",Confusion_Matrix1)


score 0.8735555555555555
Confusion Matrix [[717   5  26  28   4   2 111   1   6   0]
 [  2 878   3  13   0   0   3   0   1   0]
 [  8   1 733   6  79   1  69   1   2   0]
 [ 23  10  17 786  34   0  30   0   0   0]
 [  1   2  79  23 716   0  74   0   5   0]
 [  0   0   1   1   0 853   1  27   2  15]
 [128   3  64  22  48   0 621   1  12   1]
 [  0   0   0   0   0  22   0 860   2  16]
 [ 11   0   4   4   7   9   8   3 853   1]
 [  0   1   0   1   0   9   0  44   0 845]]


In [ ]:
#By using data preprocessed with PCA 

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
MLP2=MLPClassifier()
MLP2.fit(train_data_pca,train_labels)

mlp_predict2 = MLP2.predict(test_data_pca)
score2 = MLP2.score(test_data_pca,test_labels)
print("score", score2)

Confusion_Matrix2 = metrics.confusion_matrix(test_labels, mlp_predict2)
print("Confusion Matrix",Confusion_Matrix2)

score 0.30955555555555553
Confusion Matrix [[571  16  71  40  28  14 134   8   7  11]
 [ 29 555  20 280   5   2   4   0   5   0]
 [110  22 105  27 166  62  62   7 209 130]
 [133  55 206 285 142  10  61   2   1   5]
 [ 61  26 115  42 292  19 105   4 143  93]
 [  4   6   2   5  15 356  43 260  97 112]
 [225  19 104  32 114  49 139   5  68 145]
 [  3  15   4   0   8 247   5 310 266  42]
 [ 11  22  67   9  60  94  80  91 149 317]
 [  0   0  26   0  77 346 146  55 226  24]]


In [ ]:
#By using data preprocessed with SVD

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
MLP3=MLPClassifier()
MLP3.fit(train_data_svd,train_labels)

mlp_predict3 = MLP3.predict(test_data_svd)
score3 = MLP3.score(test_data_svd,test_labels)
print("score", score3)

Confusion_Matrix3 = metrics.confusion_matrix(test_labels, mlp_predict3)
print("Confusion Matrix",Confusion_Matrix3)

score 0.6016666666666667
Confusion Matrix [[500   9  29  85  59  10 110   8  52  38]
 [  9 704   3  87   5  22   4  59   5   2]
 [ 59   0 397  12 158  10 196   2  58   8]
 [ 40 192  12 406  81  48  35  48  28  10]
 [ 43   7  88  67 496   7 145   6  35   6]
 [ 12  15   0  21   7 659  38  89  30  29]
 [158   3  81  50 136  26 360   2  76   8]
 [  6  38   0  24   0  81   1 591  10 149]
 [ 93   8  26  56  52  30  55  17 506  57]
 [ 35   1   1   1   5  12   5  31  13 796]]


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
