In [ ]:
import tensorflow as tf
from tensorflow import keras

from keras.datasets import fashion_mnist
from keras.utils.np_utils import to_categorical

#load dataset
(trainX, trainY), (testX, testY) = fashion_mnist.load_data()
#load train and test dataset
def load_dataset():
    #load dataset
    (trainX, trainY), (testX, testY) = fashion_mnist.load_data()
    #reshape dataset to have a single channel
    trainX = trainX.reshape((trainX.shape[0], 28, 28, 1))
    testX = testX.reshape((test.shape[0], 28, 28, 1))
    trainY = to_categorical(trainY)
    testY = to_categorical(testY)
    return trainX, trainY, testX, testY
    

seed = 9

from sklearn.model_selection import StratifiedShuffleSplit

data_split = StratifiedShuffleSplit(test_size = 0.5,random_state = seed)
for train_index, test_index in data_split.split(trainX, trainY):
    
    split_data_92, split_data_8 = trainX[train_index], trainX[test_index]
    
    split_label_92, split_label_8 = trainY[train_index], trainY[test_index]
train_test_split = StratifiedShuffleSplit(test_size = 0.3,random_state = seed)

#data splitting
for train_index, test_index in train_test_split.split(split_data_8,split_label_8):
    
    train_data_70, test_data_30 = split_data_8[train_index], split_data_8[test_index]
    
    train_label_70, test_label_30 = split_label_8[train_index], split_label_8[test_index]
train_data = train_data_70

train_labels = train_label_70

test_data = test_data_30

test_labels = test_label_30
print('train_data : ',train_data.shape)
print('train_labels : ',train_labels.shape)
print('test_data : ',test_data.shape)
print('test_labels : ',test_labels.shape)

import numpy as np

#data preprocessing
#PREPROCESSING WITH NORMALIZATION FUNCTION
def normalize(data, eps=1e-8):
    data -= data.mean(axis=(0,1,2),keepdims=True)
    std = np.sqrt(data.var(axis=(0, 1, 2), ddof=1, keepdims=True))
    std[std < eps] = 1
    data /= std
    return data
train_data=train_data.astype('float64')
test_data=test_data.astype('float64')
#calling the function
train_data = normalize(train_data)
test_data = normalize(test_data)
#printing the slope of train data and test data
print('train_data: ', train_data.shape)
print('test_data: ',test_data.shape)


#PREPROCESSING WITH PCA
#computing whitening matrix
train_data_flat = train_data.reshape(train_data.shape[0], -1)
test_data_flat = test_data.reshape(test_data.shape[0], -1)
print('train_data_flat: ',train_data_flat.shape)
print('test_data_flat: ',test_data_flat.shape)

train_data_flat_t = train_data_flat
test_data_flat_t = test_data_flat

from sklearn.decomposition import PCA

train_data_pca =PCA(n_components=min(train_data_flat.shape)).fit_transform(train_data_flat)
test_data_pca =PCA(n_components=min(test_data_flat.shape)).fit_transform(test_data_flat)
print(train_data_pca.shape)
print(test_data_pca.shape)


#PREPROCESSING WITH SVD
from skimage import color

def svdFeatures(input_data):
    svdArray_input_data=[]
    size = input_data.shape[0]
    for i in range (0,size):
        img=color.rgb2gray(input_data[i])
        u, s, v = np.linalg.svd(img, full_matrices=False)
        S=[s[i] for i in range(28)]
        svdArray_input_data.append(S)
        svdMatrix_input_data=np.matrix(svdArray_input_data)
    return svdMatrix_input_data
#apply SVD for train and test data
train_data_svd=svdFeatures(train_data)
test_data_svd=svdFeatures(test_data)
print(train_data_svd.shape)
print(test_data_svd.shape)



4431872/4422102 [==============================] - 0s 0us/step
train_data :  (21000, 28, 28)
train_labels :  (21000,)
test_data :  (9000, 28, 28)
test_labels :  (9000,)
train_data:  (21000, 28, 28)
test_data:  (9000, 28, 28)
train_data_flat:  (21000, 784)
test_data_flat:  (9000, 784)
(21000, 784)
(9000, 784)
(21000, 28)
(9000, 28)


In [ ]:
#By using data preprocessed with NORMALIZATION FUNCTION

In [ ]:
from sklearn import svm
from sklearn import metrics
clf1 = svm.SVC(gamma=0.001,probability=True)
clf1.fit(train_data_flat_t, train_labels)

predicted1=clf1.predict(test_data_flat_t)
score1= clf1.score(test_data_flat_t,test_labels)
print("score",score1)

Confusion_Matrix1 = metrics.confusion_matrix(test_labels, predicted1)
print("Confusion Matrix",Confusion_Matrix1)

score 0.8675555555555555
Confusion Matrix [[747   0  16  48   3   1  77   0   8   0]
 [  7 864   1  23   1   0   4   0   0   0]
 [ 12   0 700   7  99   1  75   0   6   0]
 [ 37   5   9 797  33   0  17   0   2   0]
 [  0   1  73  34 726   0  63   0   3   0]
 [  0   0   0   1   0 859   0  29   0  11]
 [168   1  76  27  59   1 555   0  13   0]
 [  0   0   0   0   0  22   0 840   2  36]
 [  2   0   2   4   2   3  20   3 864   0]
 [  1   0   1   0   0   6   0  36   0 856]]


In [ ]:
#By using data preprocessed with PCA 

In [ ]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
clf2 = svm.SVC(gamma=0.001,probability=True)
clf2.fit(train_data_pca, train_labels)

predicted2=clf2.predict(test_data_pca)
score2= clf2.score(test_data_pca,test_labels)
print("score",score2)

Confusion_Matrix2 = confusion_matrix(test_labels, predicted2)
print("Confusion Matrix",Confusion_Matrix2)

score 0.387
Confusion Matrix [[644  41  29  69  16   4  72   3  13   9]
 [ 16 579   6 290   1   1   1   0   6   0]
 [ 58   0 159  59 171   6  82  13 179 173]
 [115  65  83 487 108   1  37   0   3   1]
 [ 22   5 171  64 251   4 158   3 124  98]
 [  0   0   0   1   1 261   6 529  94   8]
 [201  19 102  79  93   7 167  14  69 149]
 [  0   0   1   0   0 183   0 615 101   0]
 [ 28   0 111  11  54  98  39  83 320 156]
 [  0   0  21   0  40 324  40  11 464   0]]


In [ ]:
#By using data preprocessed with SVD

In [ ]:
from sklearn import svm
from sklearn import metrics
clf3 = svm.SVC(gamma=0.001,probability=True)
clf3.fit(train_data_svd, train_labels)

predicted3=clf3.predict(test_data_svd)
score3= clf3.score(test_data_svd,test_labels)
print("score",score3)

Confusion_Matrix3 = metrics.confusion_matrix(test_labels, predicted3)
print("Confusion Matrix",Confusion_Matrix3)

score 0.4908888888888889
Confusion Matrix [[311  38  22  62  62  54 146 115  39  51]
 [  8 681   6  42  18  76   3  61   2   3]
 [ 30  11 316  49 169 103 149  18  45  10]
 [ 33 297  39 167  86 117  20  88  41  12]
 [ 35  29 121  48 377  98  74  50  52  16]
 [  2  54   1   4   4 696  30  82   4  23]
 [ 87  14 125  59 118 126 225  44  88  14]
 [ 21  67   0  19   3 155   4 476   6 149]
 [ 51  24  20  76  38 101  43  65 400  82]
 [ 38   0   0   0   5  31   6  37  14 769]]
